### ISSUE TITLE
ERROR while running quickstart

### ISSUE THREAD

**Issue by ESCA001** [FraunhoferMEVIS/MedicalMultitaskModeling#1]
Hi, I got "AssertionError: For non-interactive jobs, the job config must be provided using the environment variable MLOPS_JSON_quickstart."when I run "config = HyperParameters.load_config(env)" in quickstart.ipynb like this:
![image](https://github.com/user-attachments/assets/4c026188-c99c-420f-a3e1-3f014beccb26)
I followed your instructions and used venv to start the whole project.
I would appreciate it if you could reply!

**Comment by Telcrome** [comment]
Hi, thanks for pointing this out! We will consider changing the error message to something more useful in this case.

You can solve the problem by setting the `LOCAL_DEV_ENV` environment variable to true, which tells the framework that you are in an interactive environment, as done in the Quickstart development container: https://github.com/FraunhoferMEVIS/MedicalMultitaskModeling/blob/main/copier_template/%7B%7Bproject_name%7D%7D/.devcontainer/devcontainer.json.jinja#L11

**Comment by ESCA001** [comment]
Thanks a lot for your kind reply! I’ve solved that with your help.在 2024年9月2日，19:46，J. Raphael Schäfer ***@***.***> 写道：﻿
Closed #1 as completed.

**Comment by 3usi9** [comment]
> Hi, thanks for pointing this out! We will consider changing the error message to something more useful in this case.
> 
> You can solve the problem by setting the `LOCAL_DEV_ENV` environment variable to true, which tells the framework that you are in an interactive environment, as done in the Quickstart development container: https://github.com/FraunhoferMEVIS/MedicalMultitaskModeling/blob/main/copier_template/%7B%7Bproject_name%7D%7D/.devcontainer/devcontainer.json.jinja#L11

The value of the variable should be "True" instead of "true" for parsing correctly :)
