### ISSUE TITLE
Questions Regarding MTL-Based Encoder and Model Export

### ISSUE THREAD

**Issue by git-ubaid** [FraunhoferMEVIS/MedicalMultitaskModeling#3]
Hi there! I’m a research scholar and recently came across your published work, "TISSUE CONCEPTS: SUPERVISED FOUNDATION MODELS IN COMPUTATIONAL PATHOLOGY." I found it incredibly insightful, which led me to explore your GitHub repository.

I have a couple of questions regarding the MTL-based encoder while running your code:

1. **Model Export Error:** I ran the code as is in a virtual environment with the default settings, and the training on the MNIST dataset completed successfully. However, I encountered an error when trying to export the model using the following line:
![chk_1](https://github.com/user-attachments/assets/322ff5f4-22b4-4e6b-97c8-7a5e124e0884)

Could you please provide some guidance on how to resolve this issue?
![chk_2](https://github.com/user-attachments/assets/50129906-b56e-4ec9-ad68-8a92d9d356a1)

2. **Retraining and Fine-Tuning:** Additionally, I would appreciate any code/guidelines on how to use the resources provided in this repository to retrain and fine-tune the model using MTL while using at least two different data sources/datasets.
e.g.  NCT-CRC-HE100K (for classification) & CRAG (for segmentation)

Thank you for your time and assistance. I look forward to your response!

**Comment by Telcrome** [comment]
Hi! Can you try loading using the string representation of the path? `module_dict = trainer.save_blocks_native("./all_blocks.pt", only_inference=True)`. We made some updates and forgot to update this cell of the tutorial

**Comment by git-ubaid** [comment]
Thank you very much for your response regarding this issue. As I continue to explore the project, I appreciate your insights on any potential challenges I may encounter.
I successfully resolved the first point of issue #3 (storing the trainer.save_blocks_native()), like:
![issue3Response](https://github.com/user-attachments/assets/e3a3607e-41de-40cf-bc45-135eac228399)


thanks to your guidance, which provided me with a fresh perspective. However, I still need your input on the second point of issue #3. I will refine my query regarding it and repost it as an issue for your review.
Thank you again for your support!

**Comment by git-ubaid** [comment]
First of all I appreciate your response to part 1 of issue # 3 that I
encountered. Following is the query explaining part 2 of the issue # 3.

*Retraining and Fine-Tuning the MTL based pipeline:*
While exploring the contribution of this repository, I noticed that the
quickstart.ipynb guide does not provide code or guidelines for training the
MTL-based pipeline with two separate datasets simultaneously. For example,
I want to fine-tune the Tissue Concepts Encoder while training a Multi-Task
Learning (MTL) pipeline that includes both a classification dataset and a
segmentation dataset.
As this work focuses on the testing of MTL based encoder via utilizing
Weakly supervised MIL heads attached to shared encoder, I wanted to explore
the direction of using this MTL based shared encoder for Multi task
simultaneous output generation.

Could you please provide* guidance on how to use this repository to retrain
and fine-tune the model with MTL*, specifically when working with at least
two different data sources for simultaneous output generation? For
instance, I would like to use PathMNIST for classification and the SemiCol
Challenge dataset for segmentation.

Any code snippets or guidelines would be greatly appreciated!
